name: CI Front-end

on:
  push:
    branches:
      - 'main'
    paths:
      - 'front-end/**'
  pull_request:
    paths:
      - 'front-end/**'
  workflow_call:
  
  
jobs:
  test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up node
          uses: actions/setup-node@v3
          with:
            node-version: 16
        - name: Compilation, Test
          working-directory: front-end/
          run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
    package:
      needs: test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up node
          uses: actions/setup-node@v3
          with:
            node-version: 16
        - name: Compilation, Package
          working-directory: front-end/
          run: npm run build --prod
    deploy:
    needs: package
    runs-on: ubuntu-latest
    name: Deploy Railsway
    steps: 
      - uses: actions/checkout@v3
      - name: Set up node
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Instalação do cliente Railway
        run: npm install -g @railway/cli
      - name: Deploy
        working-directory: front-end/dist/sgcmapp
        run: railway up --detach --service sgcm-welligton-frontend
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
  
 
